In [2]:
import os
from dotenv import load_dotenv
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from RequestGuard import RequestGuard as RG

In [3]:
url = "https://www.boxofficemojo.com/brand/bn3732077058/"
rg = RG(url)
if rg.can_follow_link(url):
    print("robot.txt allows scraping for this page")

robot.txt allows scraping for this page

In [4]:
r = requests.get(url)
print(r.status_code)

200

In [5]:
soup = BeautifulSoup(r.text)
# print(soup)
container = soup.find('div', {'class': 'a-section imdb-scroll-table mojo-gutter'})
# print(container)

In [6]:
items = container.find_all('tr')
ranks, titles, gross, max_theaters, opening_earnings, opening_num_thtrs, release_dates, studios = [], [], [], [], [], [], [], []
for row in items[1:]:
    rank = row.find('td', class_='mojo-field-type-rank').text
    ranks.append(rank)
    title = row.find('td', class_='mojo-field-type-release').text
    titles.append(title)
    life_gross = row.find('td', class_='a-text-right mojo-field-type-money mojo-sort-column mojo-estimatable').text
    gross.append(life_gross)
    max_theater = row.find('td', class_='a-text-right mojo-field-type-positive_integer').text
    max_theaters.append(max_theater)
    opening = row.find('td', class_='a-text-right mojo-field-type-money').text
    opening_earnings.append(opening)
    opening_num_thtr = row.find('td', class_='a-text-right mojo-field-type-positive_integer').text
    opening_num_thtrs.append(opening_num_thtr)
    release_date = row.find('td', class_='mojo-field-type-date').text
    release_dates.append(release_date)
    studio = row.find('td', class_='mojo-field-type-release_studios').text.strip('\n')
    studios.append(studio)

In [7]:
df = pd.DataFrame({'Rank': ranks, 'Title': titles, 'Gross Income': gross, 'Max Theaters': max_theaters, 'Opening Earnings': opening_earnings, 'Opening Num Theaters': opening_num_thtrs, 'Release Dates': release_dates, 'Studio': studios}).drop_duplicates()
df

,Rank,Title,Gross Income,Max Theaters,Opening Earnings,Opening Num Theaters,Release Dates,Studio
0,1,Avengers: Endgame,"$858,373,000","4,662","$357,115,007","4,662","Apr 26, 2019",Walt Disney Studios Motion Pictures
1,2,Spider-Man: No Way Home,"$804,793,477","4,336","$260,138,569","4,336","Dec 17, 2021",Sony Pictures Releasing
2,3,Black Panther,"$700,059,566","4,084","$202,003,951","4,084","Feb 16, 2018",Walt Disney Studios Motion Pictures
3,4,Avengers: Infinity War,"$678,815,482","4,474","$257,698,183","4,474","Apr 27, 2018",Walt Disney Studios Motion Pictures
4,5,The Avengers,"$623,357,910","4,349","$207,438,708","4,349","May 4, 2012",Walt Disney Studios Motion Pictures
...,...,...,...,...,...,...,...,...
71,72,Columbia 100th Anniversary SeriesColumbia 100t...,"$6,013,515",466,"$18,856",466,"Apr 15, 2024",Sony Pictures Releasing
79,80,Inhumans,"$1,521,787",393,"$1,135,440",393,"Sep 1, 2017",IMAX
80,81,Guardians of the Galaxy2020 Re-release,"$542,000","1,560","$406,000","1,560","Nov 13, 2020",Walt Disney Studios Motion Pictures
81,82,Iron Man2020 Re-release,"$430,000",462,"$430,000",462,"Jul 17, 2020",Walt Disney Pictures
82,83,Black Panther2020 Re-release,"$367,000",421,"$367,000",421,"Jul 10, 2020",Walt Disney Pictures

In [8]:
df.to_csv('datasets/marvel_movies.csv')