In [2]:
import os
from dotenv import load_dotenv
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from RequestGuard import RequestGuard as RG

In [3]:
url = "https://www.boxofficemojo.com/brand/bn3295869442/"
rg = RG(url)
if rg.can_follow_link(url):
    print("robot.txt allows scraping for this page")

robot.txt allows scraping for this page

In [4]:
r = requests.get(url)
print(r.status_code)

200

In [5]:
soup = BeautifulSoup(r.text)
# print(soup)
container = soup.find('div', {'class': 'a-section imdb-scroll-table mojo-gutter'})
# print(container)

In [6]:
items = container.find_all('tr')
ranks, titles, gross, max_theaters, opening_earnings, opening_num_thtrs, release_dates, studios = [], [], [], [], [], [], [], []
for row in items[1:]:
    rank = row.find('td', class_='mojo-field-type-rank').text
    ranks.append(rank)
    title = row.find('td', class_='mojo-field-type-release').text
    titles.append(title)
    life_gross = row.find('td', class_='a-text-right mojo-field-type-money mojo-sort-column mojo-estimatable').text
    gross.append(life_gross)
    max_theater = row.find('td', class_='a-text-right mojo-field-type-positive_integer').text
    max_theaters.append(max_theater)
    opening = row.find('td', class_='a-text-right mojo-field-type-money').text
    opening_earnings.append(opening)
    opening_num_thtr = row.find('td', class_='a-text-right mojo-field-type-positive_integer').text
    opening_num_thtrs.append(opening_num_thtr)
    release_date = row.find('td', class_='mojo-field-type-date').text
    release_dates.append(release_date)
    studio = row.find('td', class_='mojo-field-type-release_studios').text.strip('\n')
    studios.append(studio)

In [7]:
df = pd.DataFrame({'Rank': ranks, 'Title': titles, 'Gross Income': gross, 'Max Theaters': max_theaters, 'Opening Earnings': opening_earnings, 'Opening Num Theaters': opening_num_thtrs, 'Release Dates': release_dates, 'Studio': studios})
df

,Rank,Title,Gross Income,Max Theaters,Opening Earnings,Opening Num Theaters,Release Dates,Studio
0,1,Frozen II,"$477,373,578","4,440","$130,263,358","4,440","Nov 22, 2019",Walt Disney Studios Motion Pictures
1,2,Frozen,"$400,738,009","3,742","$243,390","3,742","Nov 22, 2013",Walt Disney Studios Motion Pictures
2,3,Zootopia,"$341,268,248","3,959","$75,063,401","3,959","Mar 4, 2016",Walt Disney Studios Motion Pictures
3,4,Moana,"$248,757,044","3,875","$56,631,401","3,875","Nov 23, 2016",Walt Disney Studios Motion Pictures
4,5,Big Hero 6,"$222,527,828","3,773","$56,215,889","3,773","Nov 7, 2014",Walt Disney Studios Motion Pictures
5,6,Ralph Breaks the Internet,"$201,091,711","4,017","$56,237,634","4,017","Nov 21, 2018",Walt Disney Studios Motion Pictures
6,7,Tangled,"$200,821,936","3,603","$48,767,052","3,603","Nov 24, 2010",Walt Disney Studios Motion Pictures
7,8,Wreck-It Ralph,"$189,422,889","3,752","$49,038,712","3,752","Nov 2, 2012",Walt Disney Studios Motion Pictures
8,9,Bolt,"$114,053,579","3,654","$26,223,128","3,654","Nov 21, 2008",Walt Disney Studios Motion Pictures
9,10,The Princess and the Frog,"$104,400,899","3,475","$786,190","3,475","Nov 25, 2009",Walt Disney Studios Motion Pictures
10,11,Meet the Robinsons,"$97,822,171","3,435","$25,123,781","3,435","Mar 30, 2007",Walt Disney Studios Motion Pictures
11,12,Encanto,"$96,093,622","3,980","$27,206,494","3,980","Nov 24, 2021",Walt Disney Studios Motion Pictures
12,13,Raya and the Last Dragon,"$54,723,032","2,375","$8,502,498","2,375","Mar 5, 2021",Walt Disney Studios Motion Pictures
13,14,Winnie the Pooh,"$26,692,846","2,405","$7,857,076","2,405","Jul 15, 2011",Walt Disney Studios Motion Pictures
14,15,Frozen2020 Re-release,"$215,000","1,367","$120,000","1,367","Nov 25, 2020",Walt Disney Studios Motion Pictures

In [8]:
df.to_csv('datasets/disney_animation_movies.csv')